addSbtPlugin("io.get-coursier"   % "sbt-coursier"  % "1.1.0-M4")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "1.4.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.4")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.11")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "0.14.10")
