package com.sageserpent.plutonium.efficient

import com.sageserpent.plutonium.{WorldBehaviours, WorldEfficientInMemoryImplementationResourceAmericium}

class WorldBehavioursUsingWorldEfficientInMemoryImplementation
    extends WorldBehaviours
    with WorldEfficientInMemoryImplementationResourceAmericium
